import { combineReducers } from 'redux';
import loggedReducer from './loggedReducer';
import cartReducer from './cartReducer';
import homeFilterReducer from './homeFilterReducer';
import newRestReducer from './newRestReducer';
import {
  signupApi,
  signinApi,
  signoutApi,
  getRestaurantInfoApi,
  getDishesApi,
  createDishApi,
  updateDishApi,
  updateRestaurantInfoApi,
  getRestaurantOrdersApi,
  updateOrderStatusApi,
  deleteDishApi,
  getRestaurantsListApi,
  addToCartApi,
  addNewToCartApi,
  getCartApi,
  getOrderDetailsApi,
  placeOrderApi,
  myOrdersApi,
  getUserProfileApi,
  updateUserInfoApi,
  addToFavoritesApi,
  removeFromFavoritesApi,
  getFavoritesApi,
  getAllAddressesApi,
  getRestaurantDeliveryApi,
  addNewAddressApi,
  cancelMyOrderApi,
  getOrderCountApi,
} from './apiReducers';

const reducers = combineReducers({
  loggedReducer,
  cartReducer,
  homeFilterReducer,
  newRestReducer,
  signupApi,
  signinApi,
  signoutApi,
  getRestaurantInfoApi,
  getDishesApi,
  createDishApi,
  updateDishApi,
  updateRestaurantInfoApi,
  getRestaurantOrdersApi,
  updateOrderStatusApi,
  deleteDishApi,
  getRestaurantsListApi,
  addToCartApi,
  addNewToCartApi,
  getCartApi,
  getOrderDetailsApi,
  placeOrderApi,
  myOrdersApi,
  getUserProfileApi,
  updateUserInfoApi,
  addToFavoritesApi,
  removeFromFavoritesApi,
  getFavoritesApi,
  getAllAddressesApi,
  getRestaurantDeliveryApi,
  addNewAddressApi,
  cancelMyOrderApi,
  getOrderCountApi,
});

export default reducers;
